---
abstract: 'like File::Path but print to STDERR'
author:
  - 'Written by Mark Fowler <mark@twoshortplanks.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Path-Stderr
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.005
resources:
  homepage: http://github.com/2shortplanks/File-Path-Stderr/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/2shortplanks/File-Path-Stderr.git
version: 2.00
