--- #YAML:1.0
name: File-Path-Stderr
version: 1.00
license: perl
distribution_type: module
requires: {}
recommends: {}
build_requires: {}
conflicts: {}
provides:
  File::Path::Stderr:
    file: lib/File/Path/Stderr.pm
    version: 1.00
generated_by: Module::Build version 0.18_02
